# Trunk.toml - Configuration for trunk build tool

[build]
# The index HTML file to use
target = "beamterm-renderer/index.html"
# The output directory for the build
dist = "dist"
# Whether to include hash in filenames
filehash = true

[watch]
# Files to watch for changes during development
watch = [
    "beamterm-renderer/src",
    "beamterm-data/src",
    "beamterm-renderer/Cargo.toml",
    "beamterm-data/Cargo.toml",
    "Cargo.toml"
]
# Files to ignore when watching
ignore = [
    "target",
    "dist",
    "data/*.atlas"
]

[serve]
# The port to serve on during development
port = 8080
# Open the browser automatically
open = false

[clean]
# The output directory to clean
dist = "dist"
# Cargo build directory
cargo = true

[[hooks]]
# Ensure font atlas exists before building
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "[ -f data/bitmap_font.atlas ] || (cd beamterm-atlas && cargo run --release -- 1 15 1.0)"]