[package]
name = "bitmap-font"
version = "0.1.0"
edition = "2021"

[dependencies]
font-atlas = { path = "../font-atlas" }
cosmic-text = "0.11.0" 
image = { workspace = true }
serde_json = { workspace = true }
color-eyre = "0.6.4"

[[bin]]
name = "bitmap-font"
path = "src/main.rs"
