[package]
name = "bitmap-font"
version = "0.1.0"
edition = "2021"

[dependencies]
font-atlas = { path = "../font-atlas" }
cosmic-text = "0.14.2"
image = { workspace = true }
color-eyre = "0.6.4"
unicode-segmentation = "1.12.0"

[[bin]]
name = "bitmap-font"
path = "src/main.rs"
