name: 🧪 CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Check code formatting
  fmt:
    name: 🎨 Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  # Run clippy lints
  clippy:
    name: 📎 Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  # Run tests for native targets
  test-native:
    name: 🧪 Test Native
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: 🔧 Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig libfontconfig-dev
      - name: Run tests
        run: cargo test --workspace --exclude beamterm-renderer

  # Build and test WASM targets
  build-wasm:
    name: 🕸️ Build WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2

      # Install required tools
      - name: 📦 Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: 📦 Install trunk
        run: |
          wget -qO- https://github.com/trunk-rs/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
          sudo mv trunk /usr/local/bin/

      # Install system dependencies for font handling
      - name: 🔧 Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig libfontconfig-dev fonts-noto fonts-noto-color-emoji

      # Generate font atlas
      - name: 🎨 Generate font atlas
        run: |
          cd beamterm-atlas
          # Build the atlas generator
          cargo build --release --bin beamterm-atlas
          # Generate atlas (using first available font)
          echo "1" | cargo run --release --bin beamterm-atlas -- 1 15 1.0
          # Verify the atlas was created
          cargo run --release --bin verify-atlas

      # Build WASM renderer
      - name: 🔨 Build beamterm-renderer for WASM
        run: |
          cd beamterm-renderer
          cargo build --target wasm32-unknown-unknown --release

      # Build with trunk for web deployment
      - name: 🌐 Build with trunk
        run: trunk build --release

      # Upload build artifacts
      - name: 📤 Upload WASM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: dist/

      - name: 📤 Upload font atlas
        uses: actions/upload-artifact@v4
        with:
          name: font-atlas
          path: data/bitmap_font.atlas

  # Documentation build
  docs:
    name: 📚 Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: 🔧 Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig libfontconfig-dev
      - name: 📚 Build docs
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs
      - name: 📤 Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: target/doc/

  # publish:
  #   name: 📦 Publish to crates.io
  #   runs-on: ubuntu-latest
  #   needs: [fmt, clippy, test-native, build-wasm]
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dtolnay/rust-toolchain@stable
  #     - name: Install system dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y fontconfig libfontconfig-dev
  #     - name: Publish beamterm-atlas
  #       run: cargo publish -p beamterm-atlas
  #       env:
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  #     - name: Wait for crates.io
  #       run: sleep 30
  #     - name: Publish beamterm-renderer
  #       run: cargo publish -p beamterm-renderer
  #       env:
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}