name: 🌐 Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v5

      - name: 🦀 Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: 📦 Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 🔧 Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig libfontconfig-dev zsh fonts-noto fonts-noto-color-emoji

      - name: 📦 Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: 🔧 Make scripts executable
        run: |
          chmod +x build.zsh
          chmod +x scripts/*.zsh

      - name: 🔧 Setup JS environment
        run: ./build.zsh setup

      - name: 🎨 Generate font atlas
        run: ./build.zsh atlas

      - name: 🌐 Build WASM packages
        run: ./build.zsh build-wasm

      - name: 🏗️ Build examples
        run: |
          cd js
          npm run build:examples

      - name: 📤 Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: js/examples-dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4