name: 📦 Release

on:
  push:
    tags:
      - 'beamterm-*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: 🎉 Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: 🏷️ Get version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: 🎉 Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

  build-release:
    name: 🔨 Build Release Assets
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            atlas_binary: beamterm-atlas
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            atlas_binary: beamterm-atlas.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            atlas_binary: beamterm-atlas

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}, wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      # Platform-specific dependencies
      - name: 🔧 Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig libfontconfig-dev fonts-noto

      # Build font atlas generator
      - name: 🔨 Build beamterm-atlas
        run: |
          cd beamterm-atlas
          cargo build --release --target ${{ matrix.target }}

      # Package atlas generator
      - name: 📦 Package atlas generator
        run: |
          mkdir -p release/beamterm-atlas-${{ matrix.target }}
          cp target/${{ matrix.target }}/release/${{ matrix.atlas_binary }} release/beamterm-atlas-${{ matrix.target }}/
          cp README.md release/beamterm-atlas-${{ matrix.target }}/
          cd release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a beamterm-atlas-${{ matrix.target }}.zip beamterm-atlas-${{ matrix.target }}
          else
            tar czf beamterm-atlas-${{ matrix.target }}.tar.gz beamterm-atlas-${{ matrix.target }}
          fi
        shell: bash

      # Upload atlas generator
      - name: 📤 Upload atlas generator
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./release/beamterm-atlas-${{ matrix.target }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_name: beamterm-atlas-${{ matrix.target }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_content_type: ${{ matrix.os == 'windows-latest' && 'application/zip' || 'application/gzip' }}

  build-wasm-release:
    name: 🕸️ Build WASM Release
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: 📦 Install tools
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wget -qO- https://github.com/trunk-rs/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
          sudo mv trunk /usr/local/bin/

      - name: 🔧 Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig libfontconfig-dev fonts-noto fonts-noto-color-emoji

      # Generate default font atlas
      - name: 🎨 Generate font atlas
        run: |
          cd beamterm-atlas
          cargo build --release
          echo "1" | cargo run --release -- 1 15 1.0

      # Build WASM with trunk
      - name: 🌐 Build WASM release
        run: trunk build --release

      # Package web build
      - name: 📦 Package web build
        run: |
          mkdir -p release
          cd dist
          tar czf ../release/beamterm-web-${{ needs.create-release.outputs.release_version }}.tar.gz *

      # Upload web build
      - name: 📤 Upload web build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./release/beamterm-web-${{ needs.create-release.outputs.release_version }}.tar.gz
          asset_name: beamterm-web-${{ needs.create-release.outputs.release_version }}.tar.gz
          asset_content_type: application/gzip

      # Upload font atlas
#      - name: 📤 Upload font atlas
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ needs.create-release.outputs.upload_url }}
#          asset_path: ./data/bitmap_font.atlas
#          asset_name: bitmap_font.atlas
#          asset_content_type: application/octet-stream